package mcp

import (
	"errors"
	"time"

	mcpapi "github.com/astralp2p/astral-go/api/mcp"
	"github.com/astralp2p/astral-go/astral"
	mcpmod "github.com/astralp2p/astrald/mod/mcp"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

type DB struct {
	*gorm.DB
}

// MigrateAgents brings the agent table to the current schema.
//
// why the old columns are dropped rather than left: the node holds no
// reachability, so a column that once carried it answers nothing and a reader
// finding one would take it for a decision something still makes.
func (db *DB) MigrateAgents() error {
	m := db.Migrator()

	if m.HasTable(&dbAgent{}) {
		for _, column := range []string{"visible", "exposed"} {
			if !m.HasColumn(&dbAgent{}, column) {
				continue
			}
			if err := m.DropColumn(&dbAgent{}, column); err != nil {
				return err
			}
		}
	}

	return db.AutoMigrate(&dbAgent{})
}

// CreateAgent inserts the agent row and stamps its creation time. The caller
// builds the row, so visibility lands in the same write as the rest of the record.
func (db *DB) CreateAgent(row *dbAgent) error {
	row.CreatedAt = time.Now()
	return db.Create(row).Error
}

func (db *DB) FindAgent(identity *astral.Identity) (row *dbAgent, err error) {
	err = db.Where("identity = ?", identity).First(&row).Error
	return
}

func (db *DB) DeleteAgent(identity *astral.Identity) error {
	tx := db.Where("identity = ?", identity).Delete(&dbAgent{})
	if tx.Error != nil {
		return tx.Error
	}
	if tx.RowsAffected == 0 {
		return gorm.ErrRecordNotFound
	}
	return nil
}

func (db *DB) ListAgents() (list []dbAgent, _ error) {
	return list, db.Find(&list).Error
}

// dbMessage is one message in one agent's box. Every message a node carries is
// two rows: the sender's and the recipient's. They differ in box and owner and
// in nothing else, and across nodes only one of them is on this machine.
//
// why one table where there were two: the two rows have different owners, and
// ownership is a predicate rather than a table name. Two tables enforced it
// with two independently-written scoping rules; one column enforces it with one.
type dbMessage struct {
	// Seq is the database's own order, assigned under the write lock, and it is
	// what a cursor pages. Nothing sets it and nothing reads it for meaning: it
	// is opaque, and only its order is a fact.
	Seq int64 `gorm:"primaryKey;autoIncrement"`

	// Box and ID are the key with Owner, and Box never changes after insert:
	// every stamp below names a column only one box may carry.
	Box string
	ID  mcpapi.MessageID

	Sender    *astral.Identity
	Recipient *astral.Identity

	// Owner is generated by the database and never written here. It reads the
	// recipient on an inbox row and the sender on an outbox row, so nothing can
	// state it wrong and no statement can update it.
	Owner *astral.Identity `gorm:"->"`

	Content string

	// ParentID names the one message this answers. Zero answers none. It is the
	// sender's claim, and a parent this node does not hold is kept as it stands.
	ParentID mcpapi.MessageID

	// CreatedAt is when this node wrote this row — the recipient's arrival on an
	// inbox row, the sender's attempt on an outbox row. It is the same fact from
	// the two sides, and it is the sort key for every list.
	//
	// why autoCreateTime is off: gorm fills a field of this name with local
	// time, where every stamp here writes UTC, and the driver stores a datetime
	// as offset-bearing text that ORDER BY compares as a string. The tag alone
	// is not enough — a zero value under it writes year one, which NOT NULL does
	// not catch — so every insert sets it explicitly.
	CreatedAt time.Time `gorm:"autoCreateTime:false;not null"`

	// ArchivedAt is the agent putting a message away: the only disposal marker,
	// on either box, and the only one with an inverse. It crosses no link.
	ArchivedAt *time.Time

	// box = inbox only.
	ReadAt          *time.Time
	ReceiptDueAt    *time.Time
	ReceiptStoredAt *time.Time

	// box = outbox only. LandedAt is the recipient's node acknowledging the
	// write — the fact the old schema called stored_at on this side while
	// calling this node's own write stored_at on the other.
	LandedAt  *time.Time
	FailedAt  *time.Time
	FetchedAt *time.Time

	// Err is a pointer so that the empty string is a refusal whose words were
	// empty, rather than the absence of a refusal.
	Err *string
}

func (dbMessage) TableName() string {
	return mcpmod.DBPrefix + "messages"
}

// errLimit bounds the recipient's node's own words. The string is another
// operator's, so it is quoted and never trusted for its length.
const errLimit = 256

// MigrateMessages creates the message table and its indexes.
//
// why the DDL is hand-written and the indexes run every time: the table carries
// a generated column, three CHECKs and a partial index, none of which a struct
// tag can express. IF NOT EXISTS makes every statement idempotent, so a restart
// costs one no-op apiece.
func (db *DB) MigrateMessages() error {
	// why an old table is renamed rather than migrated or dropped: nothing is
	// carried across, but a table already standing makes CREATE TABLE IF NOT
	// EXISTS a no-op, and every statement after it then fails against a shape
	// that has no box column. The module would fail to load, and a module that
	// fails to load is logged once and skipped — the node comes up serving its
	// agents no tools at all. Renaming leaves the old rows on disk for an
	// operator to read or drop, and lets the create path run.
	m := db.Migrator()
	for _, old := range []string{mcpmod.DBPrefix + "messages", mcpmod.DBPrefix + "outbox"} {
		if !m.HasTable(old) {
			continue
		}
		if old == mcpmod.DBPrefix+"messages" && m.HasColumn(&dbMessage{}, "box") {
			continue
		}
		if err := db.Exec("ALTER TABLE " + old + " RENAME TO " + old + "_v1").Error; err != nil {
			return err
		}
	}

	if err := db.Exec(ddlMessages).Error; err != nil {
		return err
	}
	for _, stmt := range ddlIndexes {
		if err := db.Exec(stmt).Error; err != nil {
			return err
		}
	}
	return nil
}

// InsertOutbox records a delivery about to be attempted and stamps the attempt.
//
// why the row is written before the delivery and not after: a process that dies
// mid-delivery leaves a row carrying created_at alone, which says the fate is
// unknown. Written afterwards it would leave nothing, which says the send never
// happened.
func (db *DB) InsertOutbox(row *dbMessage) error {
	row.Box = boxOutbox
	row.CreatedAt = time.Now().UTC()
	return db.Create(row).Error
}

// InsertInbox stores a delivered message and reports whether this call is the
// one that stored it.
//
// why the count and not the error: a delivery that collides with a row already
// held answers rows=0 and err=nil, and so does an honest retry. Only the caller
// can tell them apart, because only the caller holds the sender the route
// authenticated — see storeMessage.
func (db *DB) InsertInbox(row *dbMessage) (int64, error) {
	row.Box = boxInbox
	row.CreatedAt = time.Now().UTC()
	tx := db.Clauses(clause.OnConflict{DoNothing: true}).Create(row)
	return tx.RowsAffected, tx.Error
}

// why the listing is unbounded: a mailbox is the agent's own and it asked for
// this list, so nothing here is a stranger's text arriving unasked. What the
// answer costs is the agent's to spend, and a cap the caller cannot see turns
// "here is your inbox" into a claim that is silently false. The bound that
// stays is on read_messages, where the bodies are.
//
// ListMessages returns one of the owner's lists, narrowed by the query and
// ordered as that list reads.
func (db *DB) ListMessages(owner *astral.Identity, q messageQuery) (list []dbMessage, _ error) {
	return list, q.apply(db.DB, owner).
		Order(q.order()).
		Find(&list).Error
}

// ReadMany returns the owner's messages named by the refs and stamps the inbox
// ones read. Ids the owner does not hold are reported rather than refused, so
// one wrong id does not cost the rest of the batch.
//
// A message already read is returned as it stands: reading is not a claim, and
// the stamp records the first read.
func (db *DB) ReadMany(owner *astral.Identity, refs []messageRef) (rows []dbMessage, missing []messageRef, _ error) {
	seen := make(map[messageRef]bool, len(refs))

	for _, ref := range refs {
		if seen[ref] {
			continue
		}
		seen[ref] = true

		var row dbMessage
		err := db.Where("owner = ? AND box = ? AND id = ?", owner, ref.Box, ref.ID).
			Take(&row).Error
		// why the two are told apart: not-found is an id the owner does not
		// hold, which the batch tolerates and reports. Anything else is a store
		// that could not answer, and reporting that as "you do not hold this"
		// tells the agent a falsehood about its own mailbox.
		if errors.Is(err, gorm.ErrRecordNotFound) {
			missing = append(missing, ref)
			continue
		}
		if err != nil {
			return nil, nil, err
		}

		if err = db.MarkRead(owner, &row); err != nil {
			return nil, nil, err
		}

		rows = append(rows, row)
	}

	return rows, missing, nil
}

// MarkRead stamps an inbox row read, once. It is the one statement that does,
// so a body handed out anywhere says the same thing about the row it came from.
func (db *DB) MarkRead(owner *astral.Identity, row *dbMessage) error {
	if row.Box != boxInbox || row.ReadAt != nil {
		return nil
	}
	now := time.Now().UTC()
	err := db.Model(&dbMessage{}).
		Where("owner = ? AND box = ? AND id = ? AND read_at IS NULL", owner, boxInbox, row.ID).
		Update("read_at", now).Error
	if err != nil {
		return err
	}
	row.ReadAt = &now
	return nil
}

// childrenOf is the predicate every question about a message's replies narrows
// by. They share it because they must answer about the same set: a reader that
// is handed an id here and refused it one call later has been told the mailbox
// holds something it does not.
//
// why what was put away is excluded: it is excluded from every listing and from
// the park, and a reply that comes back as a child of something else would be
// the one path that undoes an archive.
//
// why a self-send is collapsed to its inbox row: an agent that writes to itself
// owns both rows of every message, so a reply to it matches twice and is
// answered twice under one id. The received copy is the one that carries the
// read stamp and the receipt, so it is the one kept — and it is kept only where
// it actually exists, so a self-send whose delivery failed still shows the copy
// the agent has.
func childrenOf(db *gorm.DB, owner *astral.Identity, parent mcpapi.MessageID) *gorm.DB {
	return db.Where("owner = ? AND parent_id = ? AND archived_at IS NULL", owner, parent).
		Where(`NOT (box = 'outbox' AND EXISTS (
			SELECT 1 FROM mcp__messages self
			WHERE self.owner = mcp__messages.owner
			  AND self.box = 'inbox'
			  AND self.id = mcp__messages.id))`)
}

// Children returns the owner's messages that name this one as their parent, in
// either box, oldest first. One level: walking further is the reader's.
func (db *DB) Children(owner *astral.Identity, parent mcpapi.MessageID, limit int) (list []dbMessage, _ error) {
	return list, childrenOf(db.DB, owner, parent).
		Order("created_at").
		Limit(limit).
		Find(&list).Error
}

// ChildIDs answers the ids of a message's direct replies, oldest first.
//
// why the whole set and not a page of it: an id is the cheap half of a message
// and it is what read_messages takes, so a reader holding all of them can ask
// for any reply in any order. A reader that cannot see a reply exists cannot
// ask for it at all, and a count alone names no id.
func (db *DB) ChildIDs(owner *astral.Identity, parent mcpapi.MessageID) (ids []mcpapi.MessageID, _ error) {
	return ids, childrenOf(db.Model(&dbMessage{}), owner, parent).
		Order("created_at").
		Pluck("id", &ids).Error
}

// Archive stamps one of the owner's messages put away and reports whether this
// call is the one that stamped it.
//
// why admission and write are one statement: a lookup then a write would race,
// and the answer the tool owes — did I put it away, or was it already away — is
// exactly what the one statement returns.
func (db *DB) Archive(owner *astral.Identity, box string, id mcpapi.MessageID) (int64, error) {
	tx := db.Model(&dbMessage{}).
		Where("owner = ? AND box = ? AND id = ? AND archived_at IS NULL", owner, box, id).
		Update("archived_at", time.Now().UTC())
	return tx.RowsAffected, tx.Error
}

// Unarchive clears the stamp. Archive is the only disposal marker an agent has,
// the ids are thirty-two characters a model will mistype, and the column is the
// recipient's own bookkeeping that crosses no link — so it is the one stamp
// here with an inverse.
func (db *DB) Unarchive(owner *astral.Identity, box string, id mcpapi.MessageID) (int64, error) {
	tx := db.Model(&dbMessage{}).
		Where("owner = ? AND box = ? AND id = ? AND archived_at IS NOT NULL", owner, box, id).
		Update("archived_at", nil)
	return tx.RowsAffected, tx.Error
}

// Each stamp is its own method and each writes once: a second call changes
// nothing, because the first answer is the one that happened.
//
// Every one of them names owner and box. Neither alone is enough: an id is the
// peer's to mint, so one owner may hold two rows under it, and a column only one
// box may carry is refused by the table rather than written to the wrong row.

// MarkReceiptDue records that a receipt is owed on this inbox row and reports
// whether this call is the one that recorded it.
func (db *DB) MarkReceiptDue(recipient *astral.Identity, id mcpapi.MessageID) (int64, error) {
	tx := db.Model(&dbMessage{}).
		Where("owner = ? AND box = ? AND id = ? AND receipt_due_at IS NULL",
			recipient, boxInbox, id).
		Update("receipt_due_at", time.Now().UTC())
	return tx.RowsAffected, tx.Error
}

// StampReceiptStored records the sender's node acknowledging our receipt.
func (db *DB) StampReceiptStored(recipient *astral.Identity, id mcpapi.MessageID) error {
	return db.Model(&dbMessage{}).
		Where("owner = ? AND box = ? AND id = ? AND receipt_stored_at IS NULL",
			recipient, boxInbox, id).
		Update("receipt_stored_at", time.Now().UTC()).Error
}

// StampLanded records the recipient's node acknowledging the write.
func (db *DB) StampLanded(sender *astral.Identity, id mcpapi.MessageID) error {
	return db.Model(&dbMessage{}).
		Where("owner = ? AND box = ? AND id = ? AND landed_at IS NULL",
			sender, boxOutbox, id).
		Update("landed_at", time.Now().UTC()).Error
}

// StampFailed records a delivery known not to have been stored.
func (db *DB) StampFailed(sender *astral.Identity, id mcpapi.MessageID) error {
	return db.Model(&dbMessage{}).
		Where("owner = ? AND box = ? AND id = ? AND failed_at IS NULL",
			sender, boxOutbox, id).
		Update("failed_at", time.Now().UTC()).Error
}

// StampFetched records the body handed out, for a sender on this node.
//
// why matching nothing is not an error: the sender may hold no row — a message
// from another node, or one whose row this node never wrote.
func (db *DB) StampFetched(sender *astral.Identity, id mcpapi.MessageID) error {
	return db.Model(&dbMessage{}).
		Where("owner = ? AND box = ? AND id = ? AND fetched_at IS NULL",
			sender, boxOutbox, id).
		Update("fetched_at", time.Now().UTC()).Error
}

// StampFetchedFrom is the receipt's admission and its write in one statement:
// the row must be ours, must be one we sent to this caller, and must not already
// be stamped. RowsAffected is the answer.
//
// why sender is spent as owner rather than kept as its own conjunct: on an
// outbox row the owner is the sender, by the generated column. Naming it twice
// would be one indexed equality and one that is not.
func (db *DB) StampFetchedFrom(sender, recipient *astral.Identity, id mcpapi.MessageID) (int64, error) {
	tx := db.Model(&dbMessage{}).
		Where("owner = ? AND box = ? AND id = ? AND recipient = ? AND fetched_at IS NULL",
			sender, boxOutbox, id, recipient).
		Update("fetched_at", time.Now().UTC())
	return tx.RowsAffected, tx.Error
}

// SetErr records the recipient's node's own words for a refusal.
//
// why the guard is IS NULL and not = ”: the column is a pointer now, and the
// empty string is a refusal whose words were empty rather than the absence of
// one. Written as `err = ”` the guard matches nothing and every refusal is
// discarded in silence.
func (db *DB) SetErr(sender *astral.Identity, id mcpapi.MessageID, text string) error {
	if len(text) > errLimit {
		text = text[:errLimit]
	}
	return db.Model(&dbMessage{}).
		Where("owner = ? AND box = ? AND id = ? AND err IS NULL", sender, boxOutbox, id).
		Update("err", text).Error
}

// SenderOf answers who wrote the row the owner holds under this id, so a caller
// can tell a delivery that collided from one that is being retried.
func (db *DB) SenderOf(owner *astral.Identity, box string, id mcpapi.MessageID) (*astral.Identity, error) {
	var row dbMessage
	err := db.Select("sender").
		Where("owner = ? AND box = ? AND id = ?", owner, box, id).
		Take(&row).Error
	return row.Sender, err
}
