package mcp

import (
	"time"

	"github.com/astralp2p/astral-go/api/mcp"
	"github.com/astralp2p/astral-go/astral"
	mcpmod "github.com/astralp2p/astrald/mod/mcp"
)

// dbMessage is one message in one agent's box. Every message a node carries is
// two rows, the sender's and the recipient's, differing in box and owner and in
// nothing else; across nodes only one of them is on this machine.
type dbMessage struct {
	// Seq is the database's own order, assigned under the write lock. It is
	// opaque: only its order is a fact, and it is what a cursor pages.
	Seq int64 `gorm:"primaryKey;autoIncrement"`

	// Box and ID are the key with Owner, and Box never changes after insert:
	// every stamp below names a column only one box may carry.
	Box string
	ID  mcp.MessageID

	Sender    *astral.Identity
	Recipient *astral.Identity

	// Owner is generated by the database — the recipient on an inbox row, the
	// sender on an outbox row — so no statement here can state or update it.
	Owner *astral.Identity `gorm:"->"`

	Content string

	// ParentID names the one message this answers. Zero answers none. It is the
	// sender's claim, and a parent this node does not hold is kept as it stands.
	ParentID mcp.MessageID

	// CreatedAt is when this node wrote the row: the recipient's arrival on an
	// inbox row, the sender's attempt on an outbox row.
	//
	// why autoCreateTime is off, and why every insert still sets it: gorm fills
	// this field with local time where every stamp writes UTC, and the driver
	// stores a datetime as text that ORDER BY compares as a string.
	CreatedAt time.Time `gorm:"autoCreateTime:false;not null"`

	// ArchivedAt is the agent putting a message away: the only disposal marker,
	// on either box, and the only one with an inverse. It crosses no link.
	ArchivedAt *time.Time

	// box = inbox only.
	ReadAt          *time.Time
	ReceiptDueAt    *time.Time
	ReceiptStoredAt *time.Time

	// box = outbox only. LandedAt is the recipient's node acknowledging the
	// write.
	LandedAt  *time.Time
	FailedAt  *time.Time
	FetchedAt *time.Time

	// Err is a pointer so that the empty string is a refusal whose words were
	// empty, rather than the absence of a refusal.
	Err *string
}

func (dbMessage) TableName() string {
	return mcpmod.DBPrefix + "messages"
}
