package mcp

import (
	"time"

	"github.com/astralp2p/astral-go/api/mcp"
	"github.com/astralp2p/astral-go/astral"
	mcpmod "github.com/astralp2p/astrald/mod/mcp"
)

// dbMessage is one message in one agent's box. Every message a node carries is
// two rows, the sender's and the recipient's, differing in box and owner and in
// nothing else; across nodes only one of them is on this machine.
type dbMessage struct {
	// Seq is the database's own order, assigned under the write lock. It is
	// opaque: only its order is a fact, and it is what a cursor pages.
	Seq int64 `gorm:"primaryKey;autoIncrement"`

	// Box and ID are the key with Owner, and Box never changes after insert:
	// every stamp below names a column only one box may carry.
	Box string
	ID  mcp.MessageID

	Sender    *astral.Identity
	Recipient *astral.Identity

	// Owner is generated by the database — the recipient on an inbox row, the
	// sender on an outbox row — so no statement here can state or update it.
	Owner *astral.Identity `gorm:"->"`

	Content string

	// ParentID names the one message this answers. Zero answers none. It is the
	// sender's claim, and a parent this node does not hold is kept as it stands.
	ParentID mcp.MessageID

	// CreatedAt is when this node wrote the row: the recipient's arrival on an
	// inbox row, the sender's attempt on an outbox row.
	//
	// why autoCreateTime is off, and why every insert still sets it: gorm fills
	// this field with local time where every stamp writes UTC, and the driver
	// stores a datetime as text that ORDER BY compares as a string.
	CreatedAt time.Time `gorm:"autoCreateTime:false;not null"`

	// ArchivedAt is the agent putting a message away: the only disposal marker,
	// on either box, and the only one with an inverse. It crosses no link.
	ArchivedAt *time.Time

	// box = inbox only.
	ReadAt          *time.Time
	ReceiptDueAt    *time.Time
	ReceiptStoredAt *time.Time

	// box = outbox only. LandedAt is the recipient's node acknowledging the
	// write.
	LandedAt  *time.Time
	FailedAt  *time.Time
	FetchedAt *time.Time

	// Err is a pointer so that the empty string is a refusal whose words were
	// empty, rather than the absence of a refusal.
	Err *string
}

func (dbMessage) TableName() string {
	return mcpmod.DBPrefix + "messages"
}

// stored renders the row as the record every layer above the store works on.
//
// why the owner column does not cross: it is derivable from the box and the two
// parties, the store scopes every read on it, and nothing above reads it.
func (row dbMessage) stored() *mcp.StoredMessage {
	m := &mcp.StoredMessage{
		Cursor:    astral.Uint64(row.Seq),
		ID:        row.ID,
		Box:       astral.String8(row.Box),
		Sender:    row.Sender,
		Recipient: row.Recipient,
		Content:   astral.String32(row.Content),
		ParentID:  row.ParentID,
		CreatedAt: astral.Time(row.CreatedAt),

		ArchivedAt:      stamp(row.ArchivedAt),
		ReadAt:          stamp(row.ReadAt),
		ReceiptDueAt:    stamp(row.ReceiptDueAt),
		ReceiptStoredAt: stamp(row.ReceiptStoredAt),
		LandedAt:        stamp(row.LandedAt),
		FailedAt:        stamp(row.FailedAt),
		FetchedAt:       stamp(row.FetchedAt),
	}
	if row.Err != nil {
		e := astral.String16(*row.Err)
		m.Err = &e
	}
	return m
}

// storedAll renders a listing.
func storedAll(rows []dbMessage) []*mcp.StoredMessage {
	list := make([]*mcp.StoredMessage, len(rows))
	for i, row := range rows {
		list[i] = row.stored()
	}
	return list
}

// stamp carries an optional instant across, absent staying absent.
func stamp(t *time.Time) *astral.Time {
	if t == nil {
		return nil
	}
	v := astral.Time(*t)
	return &v
}

// newRow is the write direction: what an insert states, and nothing the store
// stamps for itself.
func newRow(m *mcp.StoredMessage) *dbMessage {
	return &dbMessage{
		ID:        m.ID,
		Sender:    m.Sender,
		Recipient: m.Recipient,
		Content:   string(m.Content),
		ParentID:  m.ParentID,
	}
}
