package mcp

import (
	"time"

	"github.com/astralp2p/astral-go/api/mcp"
	"github.com/astralp2p/astral-go/astral"
	mcpmod "github.com/astralp2p/astrald/mod/mcp"
)

// dbMessage is one message in one agent's box. Every message a node carries is
// two rows: the sender's and the recipient's. They differ in box and owner and
// in nothing else, and across nodes only one of them is on this machine.
//
// why one table where there were two: the two rows have different owners, and
// ownership is a predicate rather than a table name. Two tables enforced it
// with two independently-written scoping rules; one column enforces it with one.
type dbMessage struct {
	// Seq is the database's own order, assigned under the write lock, and it is
	// what a cursor pages. Nothing sets it and nothing reads it for meaning: it
	// is opaque, and only its order is a fact.
	Seq int64 `gorm:"primaryKey;autoIncrement"`

	// Box and ID are the key with Owner, and Box never changes after insert:
	// every stamp below names a column only one box may carry.
	Box string
	ID  mcp.MessageID

	Sender    *astral.Identity
	Recipient *astral.Identity

	// Owner is generated by the database and never written here. It reads the
	// recipient on an inbox row and the sender on an outbox row, so nothing can
	// state it wrong and no statement can update it.
	Owner *astral.Identity `gorm:"->"`

	Content string

	// ParentID names the one message this answers. Zero answers none. It is the
	// sender's claim, and a parent this node does not hold is kept as it stands.
	ParentID mcp.MessageID

	// CreatedAt is when this node wrote this row — the recipient's arrival on an
	// inbox row, the sender's attempt on an outbox row. It is the same fact from
	// the two sides, and it is the sort key for every list.
	//
	// why autoCreateTime is off: gorm fills a field of this name with local
	// time, where every stamp here writes UTC, and the driver stores a datetime
	// as offset-bearing text that ORDER BY compares as a string. The tag alone
	// is not enough — a zero value under it writes year one, which NOT NULL does
	// not catch — so every insert sets it explicitly.
	CreatedAt time.Time `gorm:"autoCreateTime:false;not null"`

	// ArchivedAt is the agent putting a message away: the only disposal marker,
	// on either box, and the only one with an inverse. It crosses no link.
	ArchivedAt *time.Time

	// box = inbox only.
	ReadAt          *time.Time
	ReceiptDueAt    *time.Time
	ReceiptStoredAt *time.Time

	// box = outbox only. LandedAt is the recipient's node acknowledging the
	// write — the fact the old schema called stored_at on this side while
	// calling this node's own write stored_at on the other.
	LandedAt  *time.Time
	FailedAt  *time.Time
	FetchedAt *time.Time

	// Err is a pointer so that the empty string is a refusal whose words were
	// empty, rather than the absence of a refusal.
	Err *string
}

func (dbMessage) TableName() string {
	return mcpmod.DBPrefix + "messages"
}
